!!!!!!!!!!!!!!!!!!!!!!!
<ExceptionInfo ValueError({'code': -32000, 'message': 'connection already closed'}) tblen=6>
